dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.7"

install:
  - "pip install pytest"      # install pytest
  - "pip install pytest-cov"  # This plugin produces coverage reports
  - "pip install codecov"     # install codecov

script:
  # Run pytest for all tests subdirectories and check test coverage with pytest-cov:
  - pytest --cov-config=.coveragerc --cov-report term-missing --cov

after_success:
  # Generates coverage report, public repo using Travis:
  # Source: https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  - codecov