---
name: Kyu8 Build Pipeline

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - 'kyu8'

permissions:
  contents: read
  pull-requests: read


jobs:
  pytype:
    name: pytype
    uses: iKostanOrg/codewars/.github/workflows/kyu8/pytype_kyu8.yml@master
